---
title: "Reproducible Research Assignment 1"
author: "David Tam"
date: "Thursday, January 15, 2015"
output: html_document
---

Loading and preprocessing the data

```{r}
data <- read.csv(unz("activity.zip", "activity.csv"))
dataNoNA <- data[complete.cases(data),]
histoData <- aggregate(dataNoNA$steps, by=list(Date=dataNoNA$date), FUN=sum)
Q2Data <- aggregate(dataNoNA$steps, by=list(Interval=dataNoNA$interval), FUN=mean)

```

What is mean total number of steps taken per day?

For this part of the assignment, you can ignore the missing values in the dataset.

1. Make a histogram of the total number of steps taken each day
    
```{r, echo=FALSE}
barplot(histoData$x, names.arg=histoData$Date, las=2, main = "Total number of steps taken each day")
```


2. Calculate and report the mean and median total number of steps taken per day

Mean : 
```{r}
mean(histoData$x)
```

Median : 
```{r}
median(histoData$x)
```

What is the average daily activity pattern?
```{r}
plot(Q2Data, type = 'l')
```
